#!/usr/bin/env bash

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export PTERO_DEBUG=1
  shift
fi

if [ -n "$PTERO_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "ptero: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export PTERO_DIR="$(abs_dirname "$0")"
export PTERO_COMMON="${PTERO_DIR}/libexec/common-ptero"

relative_submodules="apis deployment perl-sdk services/*"
for i in $relative_submodules; do
    PTERO_SUBMODULES="$PTERO_SUBMODULES $PTERO_DIR/$i"
done
export PTERO_SUBMODULES

for i in $PTERO_SUBMODULES; do
    if [ -d "${i}/libexec" ]; then
        PATH="${i}/libexec:${PATH}"
    fi
done
export PATH="${PTERO_DIR}/libexec:${PATH}"


command="$1"
case "$command" in
'' )
    echo "Usage: $(basename $0) <SUBCOMMAND> [OPTIONS]" 1>&2
    echo 1>&2
    echo "Available subcommands:" 1>&2
    for SC in $(find $(echo $PATH | sed 's/:/ /g') -maxdepth 1 -name "ptero-*" -not -name "ptero-*-*" | xargs -n 1 basename | sed 's/^ptero-//'); do
        echo "  $SC" 1>&2
    done
    exit 1
  ;;
help )
    shift 1
    exec "$0" "$@" -h
  ;;
* )
  command_path="$(command -v "ptero-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "ptero: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac

