#!/usr/bin/env bash

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export PTERO_DEBUG=1
  shift
fi

if [ -n "$PTERO_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "ptero: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export PTERO_DIR="$(abs_dirname "$0")"
export PATH="${PTERO_DIR}/libexec:${PATH}"
export PTERO_COMMON="${PTERO_DIR}/libexec/common-ptero"


command="$1"
case "$command" in
* )
  command_path="$(command -v "ptero-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "ptero: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac

